spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myapp_db
    username: myapp_user
    password: myapp_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    check-template-location: false
