services:
  mysql:
    image: mysql:8.0
    container_name: library-db
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: myapp_user
      MYSQL_PASSWORD: myapp_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring_net

volumes:
  mysql_data:

networks:
  spring_net:
    driver: bridge
